Update zip.yml

diff --git a/.github/workflows/zip.yml b/.github/workflows/zip.yml
--- a/.github/workflows/zip.yml
+++ b/.github/workflows/zip.yml
@@ -45,41 +45,38 @@ jobs:
           cd "${GITHUB_WORKSPACE}/workspace"
           7z l firmware.zip
 
-      - name: 自动提取分区文件
+            - name: 自动提取分区文件
         run: |
           set -e  # 如果遇到错误，立即退出
           
           # 查找 boot.img 文件路径并提取
-          cd "${GITHUB_WORKSPACE}/workspace"
-          boot_path=$(7z l firmware.zip | grep -oP '.*boot.img' || true)
-          if [ -n "$boot_path" ]; then
+          boot_path=$(7z l firmware.zip | grep -oP '.*(?=boot.img)' || echo "boot.img not found")
+          if [ "$boot_path" != "boot.img not found" ]; then
             echo "找到 boot.img，开始提取"
-            cd "${GITHUB_WORKSPACE}/workspace"
             7z e firmware.zip "$boot_path" -o"${GITHUB_WORKSPACE}/workspace/output"
           else
             echo "未找到 boot.img"
+            exit 1  # 提取失败时退出
           fi
 
           # 查找 vbmeta.img 文件路径并提取
-          cd "${GITHUB_WORKSPACE}/workspace"
-          vbmeta_path=$(7z l firmware.zip | grep -oP '.*vbmeta.img' || true)
-          if [ -n "$vbmeta_path" ]; then
-            echo "找到 vbmeta.img，开始提取 "$vbmeta_path""
-            cd "${GITHUB_WORKSPACE}/workspace"
+          vbmeta_path=$(7z l firmware.zip | grep -oP '.*(?=vbmeta.img)' || echo "vbmeta.img not found")
+          if [ "$vbmeta_path" != "vbmeta.img not found" ]; then
+            echo "找到 vbmeta.img，开始提取"
             7z e firmware.zip "$vbmeta_path" -o"${GITHUB_WORKSPACE}/workspace/output"
           else
             echo "未找到 vbmeta.img"
+            exit 1  # 提取失败时退出
           fi
 
           # 查找 init_boot.img 文件路径并提取
-          cd "${GITHUB_WORKSPACE}/workspace"
-          init_boot_path=$(7z l firmware.zip | grep -oP '.*init_boot.img' || true)
-          if [ -n "$init_boot_path" ]; then
+          init_boot_path=$(7z l firmware.zip | grep -oP '.*(?=init_boot.img)' || echo "init_boot.img not found")
+          if [ "$init_boot_path" != "init_boot.img not found" ]; then
             echo "找到 init_boot.img，开始提取"
-            cd "${GITHUB_WORKSPACE}/workspace"
             7z e firmware.zip "$init_boot_path" -o"${GITHUB_WORKSPACE}/workspace/output"
           else
             echo "未找到 init_boot.img"
+            exit 1  # 提取失败时退出
           fi
 
       - name: 压缩并上传文件
